DROP TABLE IF EXISTS BUDGET;
  
CREATE TABLE BUDGET (
  id VARCHAR (20) NOT NULL,
  name VARCHAR (20) NOT NULL,
  amount FLOAT (10) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);