DROP TABLE IF EXISTS COUNTRY;
  
CREATE TABLE COUNTRY (
  id VARCHAR (50) NOT NULL,
  idFromX INT (50) NOT NULL,
  idFromY INT (50) NOT NULL,
  idFromZ INT (50) NOT NULL,
  name VARCHAR (50) NOT NULL,
  abbreviation VARCHAR (5) NOT NULL,
  createdAt TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP NOT NULL
);